config/routes.rb
Dylome::Application.routes.draw do
  root 'songs#index'
  resources :songs, only: [:new, :create, :index, :show]
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_attached_file :uploaded_file
  validates_attachment :uploaded_file, presence: true, size: {in: 0..20.megabytes}

  has_attached_file :processed_file

  validates_presence_of :name, :bpm
  validates_numericality_of :bpm, greater_than_or_equal_to: 50, less_than_or_equal_to: 200

  before_create :calculate_song_length
  before_create :dylomify

  def filename_without_extension
    if uploaded_file_file_name.present?
      uploaded_file_file_name.split('.')[0..-2].join
    end
  end

  def formatted_duration
    length.duration(false)
  end

  def song_id
    @song_id ||= (id.present? ? id : (0...8).map{(65+rand(26)).chr}.join)
  end

  def uploaded_file_copy
    unless @uploaded_file_copy && File.exists?(@uploaded_file_copy)
      original_file = if uploaded_file.queued_for_write.any?
                        uploaded_file.queued_for_write[:original].path
                      else
                        raise "No file"
                        uploaded_file.path
                      end

      @uploaded_file_copy = tmp_dir.join("#{song_id}.mp3").to_s
      FileUtils.rm @uploaded_file_copy if File.exists?(@uploaded_file_copy)
      FileUtils.copy(original_file, @uploaded_file_copy)

      @uploaded_file_copy
    end

    raise "File not copied" if (@uploaded_file_copy.nil? || !File.exists?(@uploaded_file_copy))
    @uploaded_file_copy
  end

  def calculate_song_length
    begin
      input_file = uploaded_file_copy

      # Get song length
      song_length_command = IO.popen ["ffmpeg", "-i", input_file, :err=>[:child, :out]] #we care about standard error
      result = song_length_command.read
      song_length_command.close

      # Update song length
      duration_string = result.match("Duration: ([0-9]+):([0-9]+):([0-9]+).([0-9]+)")
      hours = duration_string[1].to_i
      minutes = duration_string[2].to_i
      seconds = duration_string[3].to_i
      self.length = hours * 3600 + minutes * 60 + seconds
    ensure
      FileUtils.rm input_file if input_file && File.exists?(input_file)
    end
  end

  def dylomify(offset = 0)
    input_file = uploaded_file_copy
    output_files = []

    begin
      (offset.to_f..length).step(chunk_duration).each_with_index do |start_time, chunk_num|
        end_time = start_time + chunk_duration

        output_file = tmp_dir.join("#{song_id}-#{chunk_num}.mp3")
        output_files << output_file

        # Create chunk
        chunk_command = %W(ffmpeg -i #{input_file} -vcodec copy -acodec copy -ss #{start_time.duration} -t #{chunk_duration.duration} #{output_file})
        chunk_command = IO.popen chunk_command
        chunk_command.read
        chunk_command.close
      end

      # Write the file list
      file_list = tmp_dir.join("#{song_id}-filelist.txt")
      file_list_contents = output_files.reverse.map {|f| "file '#{f}'"}.join("\n")
      File.open(file_list, 'w') { |file| file.write(file_list_contents) }

      output_files << file_list
      output_files << input_file

      # Combine chunks
      dylomified_file = tmp_dir.join("#{uploaded_file_file_name}-dylome.mp3")
      concat_command = %W(ffmpeg -f concat -i #{file_list} -c copy #{dylomified_file})
      concat_command = IO.popen concat_command
      concat_command.read
      concat_command.close
      output_files << dylomified_file

      # Upload processed file
      self.processed_file = File.new(dylomified_file)
    ensure
      FileUtils.rm output_files
    end
  end

  def chunk_duration(num_beats = 4)
    60.to_f / bpm * num_beats
  end

  def tmp_dir
    tmp_dir = Rails.root.join('tmp', 'dylome')
    Dir::mkdir(tmp_dir) unless File.exists?(tmp_dir)
    tmp_dir
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.order('created_at DESC')
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render action: 'show', status: :created, location: @song }
      else
        format.html { render action: 'new' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :length, :bpm, :uploaded_file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dylome</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>


    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Begin page content -->
      <div class="container">
        <h1 class='center'><%= link_to 'Dylome', root_path %></h1>
        <br/>
        <%= yield %>
      </div>
    </div>

    <div id="footer">
      <div class="container">
        <div class='navbar'>
          <p class="navbar-brand">Dylome</p>
          <p class="navbar-text text-muted">Created by <%= link_to 'Kurt Preston', 'http://www.kurtpreston.com' %> and <%= link_to 'Dubi Kaufman', 'http://www.dubster.com/' %></p>

        </div>
      </div>
    </div>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <div class="field">
    <%= f.label :name, "What's the name of the song?" %><br>
    <% if @song.errors[:name].any? %>
      <div class='form-error'>Please enter the song title</div>
    <% end %>
    <%= f.text_field :name, placeholder: 'Title' %>
  </div>
  <div class="field">
    <%= f.label :bpm, "What's the BPM?" %><br>
    <% if @song.errors[:bpm].any? %>
      <div class='form-error'>Please enter BPM between 50 and 200</div>
    <% end %>
    <%= f.text_field :bpm, placeholder: '120' %>
  </div>
  <div class="field">
    <%= f.label :uploaded_file, "Select an MP3" %><br>
    <% if @song.errors[:uploaded_file].any? %>
      <div class='form-error'>Please select an MP3</div>
    <% end %>
    <%= f.file_field :uploaded_file %>
  </div>
  <div class="actions">
    <%= f.submit "Upload", class: 'btn btn-primary' %>
  </div>
  <div id="status-message"></div>
<% end %>

<script type='text/javascript'>
  $(document).ready(function() {
    $('#new_song').submit(function() {
      $('#status-message').text("Your file is being processed.  This may take a few minutes...");
      $('#new_song input[type="submit"]').attr('disabled', 'disabled');
    });
  });
</script>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p>Dylome is a tool that manipulates a sound file. The name DYLOME is the word MELODY broken into syllables (me-lo-dy) and reassembled in reverse order. The application does a similar thing to sound files. It breaks them down into small chunks and puts them together in reverse order. The most ear-pleasing results happen when the slicing matches the beat of the music.</p>

<br/>

<p class='center'>
  <%= link_to '<i class="icon-cloud-upload"></i> Upload a song'.html_safe, new_song_path, class: 'btn btn-primary' %>
</p>

<br/>
<br/>
<br/>

<h2 class='center'>Recently-uploaded songs</h2>
<table class='table centered'>
  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td>
          <strong><%= song.name %></strong><br/>
          <small class='details'>
            <%= song.formatted_duration %><br/>
            <%= song.bpm %> BPM
          </small>
        </td>
        <td>
          <div class='song-wrapper'>
            <div class='song'>
              <audio controls preload='none'>
                <source src="<%= song.uploaded_file.url %>" type="audio/mpeg">
                Your browser does not support this audio format.
              </audio>
              <div class='caption'>
                original
                <%= link_to "<i class='icon-download-alt'></i>".html_safe, song.uploaded_file.url, target: '_blank' %>
              </div>
            </div>
            <% if song.processed_file_file_name %>
              <br/>
              <div class='song'>
                <audio controls preload='none'>
                  <source src="<%= song.processed_file.url %>" type="audio/mpeg">
                  Your browser does not support this audio format.
                </audio>
                <div class='caption'>
                  dylomified
                  <%= link_to "<i class='icon-download-alt'></i>".html_safe, song.processed_file.url, target: '_blank' %>
                </div>
              </div>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/songs/new.html.erb
<h1>Upload a new song to DYLOMEify</h1>

<%= render 'form' %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @song.name %></h1>

<p>
  <strong>Duration:</strong>
  <%= @song.formatted_duration %>
</p>

<p>
  <strong>BPM:</strong>
  <%= @song.bpm %>
</p>

<h2>Original Song</h2>
<audio controls>
  <source src="<%= @song.uploaded_file.url %>" type="audio/mpeg">
  Your browser does not support this audio format.
</audio>

<h2>Dylomified Song</h2>
<% if @song.processed_file_file_name %>
  <audio controls>
    <source src="<%= @song.processed_file.url %>" type="audio/mpeg">
    Your browser does not support this audio format.
  </audio>
<% end %>